### ISSUE TITLE
Forgotten Interface File!

### ISSUE THREAD

**Issue by josua** [MicrosoftTranslator/LocalFeature-Android#2]
Hello,
You have forget to put com.microsoft.translator.service.app.ITranslatorApi interface file in /translatorlocal/src/main/java/com/microsoft/translator/service/app/ directory.
Best Regards

**Comment by tystratt** [comment]
Hi josua,

The interface is defined in the aidl file [ITranslatorApi.aidl](https://github.com/MicrosoftTranslator/Local-Feature-Android/blob/master/translatorlocal/src/main/aidl/com/microsoft/translator/service/app/ITranslatorApi.aidl)

When you build the project, it will compile the aidl file.
