### ISSUE TITLE
Are there any quotas if I use offline preloaded dictionaries?

### ISSUE THREAD

**Issue by anonym24** [MicrosoftTranslator/LocalFeature-Android#4]
This library can work offline (if you download dictionaries to your sdcard), but it still wants API key if internet is enabled

So it works fine if internet is disabled (no need even to set normal key, just random string)

**Comment by chriswendt1** [comment]
The same quotas as online consumption are expected, although not enforced while in preview. The offline API performs the translation online if the device is online, and offline if the device is offline, as long as the appropriate language pack is installed.
